site_name: 'Повышение надежности и отказоустойчивости ИТ-систем'
site_description: 'Тестирование кластеров, АС, ПАК, сервисов в промышленной эксплуатации'
site_author: Evgeniy Pogrebnyak
docs_dir: docs/
nav:
    - Главная: index.md
    - Обзор видов тестирования: testing.md
    - Опыт команды: team.md
    - Наш блог: blog/index.md
    - Контакты: contacts.md
    - About us: english.md

theme:
  name: 'material'
  icon:
    logo: material/webhook
  favicon: images/webhook-dark.png
  palette:
    primary: 'blue grey'
  language: ru

plugins:
  - search:
      lang:
        - en
        - ru

google_analytics: 
  - UA-168750267-1
  - auto
  
markdown_extensions:  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: '&copy; 2020 Eвгений Погребняк и эксперты v10n.com'
