site_name: 'v10n.com - Повышение надежности и отказоустойчивости ИТ-систем'
site_description: 'Тестирование кластеров, АС, ПАК, сервисов в промышленной эксплуатации'
site_author: Evgeniy Pogrebnyak
docs_dir: docs/
nav:
    - Главная: index.md
    - Обзор видов тестирования: testing.md
    - Цитаты о хаос-тестах: quotes.md
    - About us: english.md
theme:
  name: 'material'
  palette:
    primary: green
  language: ru

# Plugins
plugins:
  - search:
      lang:
        - en
        - ru

google_analytics: 
  - UA-168750267-1
  - auto

# Cоmmented to prevent display of github repo: 
# repo_name: 'mhausenblas/actions-sandbox'
# repo_url: 'https://github.com/mhausenblas/actions-sandbox'
