site_name: v10n.com
site_description: 'Тестирование кластеров, АС, ПАК, сервисов в промышленной эксплуатации'
site_author: Evgeniy Pogrebnyak
docs_dir: docs/
nav:
    - Начало: index.md
    - Хаос-тесты в цитатах: quotes.md
    - Виды тестирования: testing.md
    - About Us: english.md
theme:
  name: 'material'
  palette:
    primary: green

google_analytics: 
  - UA-168750267-1
  - auto

# Cmmented to prevent display of github repo: 
# repo_name: 'mhausenblas/actions-sandbox'
# repo_url: 'https://github.com/mhausenblas/actions-sandbox'
