site_name: 'Повышение надежности и отказоустойчивости ИТ-систем'
site_description: 'Тестирование кластеров, АС, ПАК, сервисов в промышленной эксплуатации'
site_author: Evgeniy Pogrebnyak
docs_dir: docs/
nav:
    - Главная: index.md
    - Обзор видов тестирования: testing.md
    - Цитаты о хаос-тестах: quotes.md
    - Опыт команды: team.md
    - Контакты: contacts.md
    - About us: english.md
    - 'Тестирование':
        - 'Больше о тестировании': blog/testing/more-about-testing.md
    - 'Примеры':
        - 'Надежность и отказоустойчивость в секторе розничной торговли': blog/cases/retail-sector-case.md
        - 'Опыт применения в сфере медицины': blog/cases/how-complex-systems-fail.md
theme:
  name: 'material'
  palette:
    primary: 'blue grey'
  language: ru

plugins:
  - search:
      lang:
        - en
        - ru

google_analytics: 
  - UA-168750267-1
  - auto
  
markdown_extensions:  
  - attr_list

copyright: '&copy; 2020 Eвгений Погребняк и эксперты v10n.com'
