site_name: 'Повышение надежности и отказоустойчивости ИТ-систем'
site_description: 'Тестирование кластеров, АС, ПАК, сервисов в промышленной эксплуатации'
site_author: Evgeniy Pogrebnyak
copyright: '&copy; 2020 Eвгений Погребняк и эксперты v10n.com'

# Note: site_url affects behavior of 404 page,
#       when transfering must change to https://v10n.com/ 
site_url: https://epogrebnyak.github.io/mkdocs-actionable/

docs_dir: docs/
nav:
    - Главная: index.md
    - Обзор видов тестирования: testing.md
    - Опыт команды: team.md
    - Наш блог: blog/index.md
    - Контакты: contacts.md
    - About us: english.md

theme:
  name: 'material'
  icon:
    logo: material/cube-outline 
  favicon: images/cube-outline.png
  palette:
    primary: 'cyan'
  language: ru

plugins:
  - search:
      lang:
        - en
        - ru
# pdf-export used to generate pdf version of the web site. 
# this is an experimental feature, the pdf file not used publically
#  - pdf-export:
#      combined: true 
#      verbose: true
#      media_type: print
#      enabled_if_env: ENABLE_PDF_EXPORT

google_analytics: 
  - UA-168750267-1
  - auto
  
markdown_extensions:  
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
